# Trump Simulator
# By Chris Schertenlieb, Sierra Dillivan, and Saxton Stafford
# CIS 365 Artificial Intellegence Project 3
# Professor Jared Moore (GVSU)

# code inspired greatly by the textgenrnn library documentation
# https://github.com/minimaxir/textgenrnn

# run the following before using this code
# pip install textgenrnn
# pip install tensorflow
# and then run 'python test.py' when finished to execute this file

from io import *
from textgenrnn import textgenrnn

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'''Code block 1 -- refining the data set'''

# this code is for taking tweets out of a
# file (tweets.txt in this example) and splitting
# them on a delimiter if necessary (\) and
# then pastes them into a new file 'newTweets.txt'
# you can skip this if you already have 'newTweets.txt'
'''tweetList = []
with open('tweets.txt', 'r', errors='replace') as f:
    for line in f:
        #print(line.encode("utf-8"))

        #newLine = line.encode('utf-8')
        #print(newLine)
        newLine = line.split('\\')
        if(len(newLine) > 1):
            tweetList.append(newLine[1])

with open('newTweets.txt', 'w') as f:
    for tweet in tweetList:
        f.write("%s\n" % tweet)'''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'''Code block 2 -- training'''

# this code creates a model.
# then trains that model on a data set called 'newTweets.txt'
# and using the passed parameters to configure.
# max_length refers to the number of characters it can look back at for context on the next word
'''textgen = textgenrnn(name="test01")
textgen.train_from_file('newTweets.txt', num_epochs=10, max_length=50, rnn_layers=2)
textgen.generate()'''

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'''Code block 3 -- generating samples from your model. '''

# create a new model by passing parameters generated by running the training code.
# then generate n tweets with a temperature t (creatvity), and using an optional prefix to nudge the rnn along
'''textgen_2 = textgenrnn(weights_path='/path/to/weights.json', vocab_path='/path/to/vocab.json', config_path='/path/to/config.json')
textgen_2.generate(n=10, prefix="THE WALL", temperature=0.6)'''


